# Generated by Django 5.2.4 on 2025-07-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
